### ISSUE TITLE
Create wireframes / mocks for the UI

### ISSUE THREAD

**Issue by kevintab95** [24HRsEscaption/5500-project#2]
Create a figma mockup / wireframes for the web UI

**Comment by KarishmaVadsaria** [comment]
Initial Prototype:
https://www.figma.com/proto/vXIxLYA9vhyA95RTBHs037/Text-to-Speech-UI?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2
