### ISSUE TITLE
front-end :fix front end UI width

### ISSUE THREAD

**Issue by 24HRsEscaption** [24HRsEscaption/5500-project#25]
what we want
![Image](https://user-images.githubusercontent.com/90473513/197437928-e6b157d1-6fb5-444a-9a03-35233517c754.png)

however when the window is larger:

![Image](https://user-images.githubusercontent.com/90473513/197437941-f1d82850-f6d5-43b7-9eb6-f9db111d18e9.png)

**Comment by KarishmaVadsaria** [comment]
As we are replacing the sliders with contour components so closing this bug.
