### ISSUE TITLE
Debug the code and locate where control parameters are applied

### ISSUE THREAD

**Issue by kevintab95** [24HRsEscaption/5500-project#9]

**Comment by ryangawei** [comment]
Control parameters are passed into VarianceAdaptor in its `forward` function (https://github.com/roedoejet/NEU-tts-2022/blob/master/model/modules.py#L102). Each parameter is used to generate the variance feature, e.g. pitch https://github.com/roedoejet/NEU-tts-2022/blob/master/model/modules.py#L118, then added to the embedding https://github.com/roedoejet/NEU-tts-2022/blob/master/model/modules.py#L121
